# Autogenerated Makefile from mmake!
CC=gcc
CFLAGS=-Werror -Wall -g -O
LIBS=

.default: all

all: main

clean:
	rm -rf main *.o

main: helpers.o linked_list.o main.o matrix.o
	$(CC) $(CFLAGS) -o $@ $^ $(LIBS)

%.o: %.c
	$(CC) $(CFLAGS) -c $^ $(LIBS)
